FROM geerlingguy/docker-ubuntu1604-ansible
RUN apt-get update \
    && apt-get install -y openssh-server openssh-client \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean
