---
- block:
  - name: Figure out which users don't want their prompt managed
    set_fact:
      _prompt_ignore_users: "{{ _prompt_ignore_users | default([])}} + [ '{{ item.name }}']"
    with_items: "{{ raxusers }}"
    when: item.use_os_prompt is defined and item.use_os_prompt

  - debug: var=_prompt_ignore_users

  - name: Assemble the list of users not wanting a managed prompt
    set_fact:
      prompt_ignore_users: "{{ _prompt_ignore_users }}"
    when: prompt_ignore_users is not defined and (_prompt_ignore_users is defined and _prompt_ignore_users|length > 0)

  - debug: var=prompt_ignore_users

  - name: Define prompt settings for production
    set_fact:
      defined_prompt: "{{ prompt_settings['production'] }}"
    when: defined_prompt is not defined and 'production' in group_names
  - name: Define prompt settings for staging
    set_fact:
      defined_prompt: "{{ prompt_settings['staging'] }}"
    when: defined_prompt is not defined and 'staging' in group_names
  - name: Define prompt settings for development
    set_fact:
      defined_prompt: "{{ prompt_settings['dev'] }}"
    when: defined_prompt is not defined and 'dev' in group_names
  - name: Define prompt settings for other
    set_fact:
      defined_prompt: "{{ prompt_settings['other'] }}"
    when: defined_prompt is not defined
  - name: Add the bash_prompt.sh template
    template:
      src: templates/bash_prompt.sh.j2
      dest: /etc/profile.d/Z99-bash_prompt.sh
      owner: root
      mode: 0644
  when: manage_prompt and manage_prompt is defined
