---
- name: ensure ssh packages installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssh
    - openssh-clients
    - openssh-server

- block:
  - name: ensure password expiration is set in login.defs
    lineinfile:
      dest: "{{ user_login_defs_path }}"
      state: present
      regexp: ^PASS_MAX_DAYS\s+\d+$
      line: "PASS_MAX_DAYS {{ user_pass_max_days }}"
      backup: yes

  - name: set accounts to auto lock if they are inactive for a number of days
    lineinfile:
      dest: "{{ user_useradd_path }}"
      state: present
      regexp: ^INACTIVE=
      line: "INACTIVE={{ user_inactive_days_pci }}"
      backup: yes
  when: "'pci' in group_names"

- block:
  - name: create users
    user:
      name: "{{ item.name }}"
      generate_ssh_key: "{{ user_gen_sshkey }}"
    with_items: "{{ raxusers }}"

  - name: authorized_keys for users
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ item.ssh_key }}"
    when: item.ssh_key is defined
    with_items: "{{ raxusers }}"
  when: raxusers|length > 0
