---
# defaults file for javiergayala.user

#  ____        __             _ _
# |  _ \  ___ / _| __ _ _   _| | |_ ___
# | | | |/ _ \ |_ / _` | | | | | __/ __|
# | |_| |  __/  _| (_| | |_| | | |_\__ \
# |____/ \___|_|  \__,_|\__,_|_|\__|___/

# Maximum number of days before password must be changed
user_pass_max_days: 90
# Path to the login.defs file
user_login_defs_path: "/etc/login.defs"
# Max number of inactive days before account is locked
user_inactive_days_pci: 45
# Path to the useradd file
user_useradd_path: "/etc/default/useradd"
# Generate SSH key
user_gen_sshkey: "yes"
# Allow Ansible to fully manage keys in authorized_keys
user_sshkey_exclusive: "no"

# sshd defaults for PCI
#          _         _
#  ___ ___| |__   __| |
# / __/ __| '_ \ / _` |
# \__ \__ \ | | | (_| |
# |___/___/_| |_|\__,_|
sshd:
  PubkeyAuthentication: 'yes'
  ChallengeResponseAuthentication: 'no'
  PasswordAuthentication: 'no'
  UsePAM: 'yes'
  ClientAliveInterval: 300
  ClientAliveCountMax: 3

#                _
#  ___ _   _  __| | ___   ___ _ __ ___
# / __| | | |/ _` |/ _ \ / _ \ '__/ __|
# \__ \ |_| | (_| | (_) |  __/ |  \__ \
# |___/\__,_|\__,_|\___/ \___|_|  |___/

# user ALL = (ALL) NOPASSWD: ALL
# user hosts = (run_as) NOPASSWD: commands
user_sudo:
  passwordless: "False"
  hosts: "ALL"
  run_as: "(ALL)"
  commands: "ALL"

#  _ __ __ ___  ___   _ ___  ___ _ __ ___
# | '__/ _` \ \/ / | | / __|/ _ \ '__/ __|
# | | | (_| |>  <| |_| \__ \  __/ |  \__ \
# |_|  \__,_/_/\_\\__,_|___/\___|_|  |___/

# initialize raxusers
raxusers: []

#  _               _                                       _
# | |__   __ _ ___| |__    _ __  _ __ ___  _ __ ___  _ __ | |_
# | '_ \ / _` / __| '_ \  | '_ \| '__/ _ \| '_ ` _ \| '_ \| __|
# | |_) | (_| \__ \ | | | | |_) | | | (_) | | | | | | |_) | |_
# |_.__/ \__,_|___/_| |_| | .__/|_|  \___/|_| |_| |_| .__/ \__|
#                         |_|                       |_|
# Whether or not to manage the bash_prompt
manage_prompt: "True"

# Dictionary containing the settings for the bash prompt based on the env.
prompt_settings:
  production:
    short_name: 'PROD'
    color: '196m'
  staging:
    short_name: 'STAGE'
    color: '11m'
  dev:
    short_name: 'DEV'
    color: '46m'
  other:
    short_name: 'UNKNOWN'
    color: '196m'
