---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint -c .yamllint .
  ansible-lint .
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    groups:
      - user_test
  - name: centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    groups:
      - user_test
  - name: debian
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
    groups:
      - user_test
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    groups:
      - user_test
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
