---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: ansible-user-default
    image: geerlingguy/docker-centos7-ansible
    groups:
      - non-pci
      - non_pci
  - name: ansible-user-default-centos6
    image: geerlingguy/docker-centos6-ansible
    groups:
      - non-pci
      - non_pci
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: "../../.vault"
  inventory:
    links:
      # group_vars: ../../../inventory/group_vars/
      host_vars: ../host_vars
  lint:
    name: ansible-lint
    options:
      force-color: True
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: junit.xml
  lint:
    name: flake8
