---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint -c .yamllint .
  ansible-lint .
platforms:
  - name: amazonlinux2
    image: amazonlinux:2
    pre_build_image: true
    groups:
      - user_test
      - amazonlinux
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    groups:
      - user_test
  - name: centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    groups:
      - user_test
  - name: debian-buster
    image: debian:buster
    pre_build_image: true
    groups:
      - user_test
      - debian
  - name: ubuntu-bionic
    image: ubuntu:bionic
    pre_build_image: true
    groups:
      - user_test
      - debian
  - name: ubuntu-eoan
    image: ubuntu:eoan
    pre_build_image: true
    groups:
      - user_test
      - debian
  - name: ubuntu-focal
    image: ubuntu:focal
    pre_build_image: true
    groups:
      - user_test
      - debian
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        users_list:
          - name: deployment
            sudoers: no
          - name: jenkins
            use_os_prompt: yes
          - name: mysudo
            sudoers: yes
verifier:
  name: ansible
