---
- name: Prepare AmazonLinux 2
  hosts: amazonlinux
  gather_facts: false
  tasks:
    - name: Install shadow-utils
      package:
        name:
          - shadow-utils
          - openssh
          - sudo
        state: present

- name: Prepare Debian
  hosts: debian
  gather_facts: false
  tasks:
    - name: Update apt cache
      raw: apt-get update -y
    - name: Install Dependencies
      raw: apt-get install -y apt-utils gcc git python3 python3-dev python3-pip libssl-dev sudo
