---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: ansible-user-ubuntu
    image: geerlingguy/docker-ubuntu1604-ansible
    groups:
      - non-pci
      - non_pci
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: "../../.vault"
  inventory:
    links:
      # group_vars: ../../../inventory/group_vars/
      host_vars: ../host_vars
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-nonpci
verifier:
  name: testinfra
  options:
    junit-xml: junit.xml
  lint:
    name: flake8
